version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/users_database?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
    mysqldb:
      platform: linux/x86_64
      image: "mysql:latest"
      restart: always
      ports:
        - 3307:3306
      environment:
         MYSQL_DATABASE: users_database
         MYSQL_USER: root
         MYSQL_PASSWORD: rootroot
         MYSQL_ROOT_PASSWORD: rootroot
